manifest:
  self:
    # This repository should be cloned to
    path: project

  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
    - name: irnas
      url-base: https://github.com/irnas

  projects:
    # the NCS repository
    - name: nrf
      repo-path: sdk-nrf
      remote: nrfconnect
      revision: v2.1.0
      import: true
    # irnas drivers and modules
    - name: irnas-versioninfo-lib
      repo-path: irnas-versioninfo-lib
      path: irnas/irnas-versioninfo-lib
      remote: irnas
      revision: v1.1.0
