manifest:
  self:
    # This repository should be cloned to
    path: project

  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
    - name: irnas
      url-base: https://github.com/irnas

  projects:
    # the NCS repository
    - name: nrf
      repo-path: sdk-nrf
      remote: nrfconnect
      # IMPORTANT: When changing NCS revision you need to change revision of
      # Zephyr project below so it matches.
      revision: v2.5.0
      import:
        name-allowlist:
          # Ignore NCS private repos, keep this list sorted alphabetically.
          # - ant
          # - bsim
          # - azure-sdk-for-c
          # - cirrus
          # - cjson
          - cmock
          # - dragoon
          # - find-my
          # - homekit
          # - hostap
          # - matter
          # - mbedtls
          # - mbedtls-nrf
          - mcuboot
          # - memfault-firmware-sdk
          # - nrf-802154
          - nrfxlib
          # - openthread
          # - sdk-lc3
          - tfm-mcuboot
          - trusted-firmware-m
          - unity
          - qcbor
          # Ignore zephyr repo as it is added below manually
          # - zephyr

    - name: zephyr
      remote: nrfconnect
      repo-path: sdk-zephyr
      revision: v3.4.99-ncs1
      import:
        # In addition to the zephyr repository itself, NCS also
        # imports the contents of zephyr/west.yml at the above
        # revision. Only the projects explicitly named in the
        # following allowlist are imported.
        #
        # Note that the zephyr west extensions (like 'build', 'flash',
        # 'debug', etc.) are automatically provided by this import, so
        # there's no need to add a redundant west-commands: key for
        # the zephyr project.
        #
        # Please keep this list sorted alphabetically.
        name-allowlist:
          # - acpica
          # - bsim
          # - babblesim_base
          # - babblesim_ext_2G4_libPhyComv1
          # - babblesim_ext_2G4_phy_v1
          # - babblesim_ext_2G4_channel_NtNcable
          # - babblesim_ext_2G4_channel_multiatt
          # - babblesim_ext_2G4_modem_magic
          # - babblesim_ext_2G4_modem_BLE_simple
          # - babblesim_ext_2G4_device_burst_interferer
          # - babblesim_ext_2G4_device_WLAN_actmod
          # - babblesim_ext_2G4_device_playback
          # - babblesim_ext_libCryptov1
          # - canopennode
          # - chre
          - cmsis
          # - edtt
          - fatfs
          # -  hal_altera
          # -  hal_ambiq
          # -  hal_atmel
          # -  hal_espressif
          # -  hal_ethos_u
          # -  hal_gigadevice
          # -  hal_infineon
          # -  hal_intel
          # -  hal_microchip
          - hal_nordic
          # -  hal_nuvoton
          # -  hal_nxp
          # -  hal_openisa
          # -  hal_quicklogic
          # -  hal_renesas
          # -  hal_rpi_pico
          # -  hal_silabs
          - hal_st # Hal for ST's sensors, not for MCU's
          # -  hal_stm32
          # -  hal_telink
          # -  hal_ti
          # -  hal_wurthelektronik
          # -  hal_xtensa
          # - liblc3
          # - libmetal
          # - littlefs
          - loramac-node
          # - lvgl
          # - lz4
          # - mbedtls
          # - mcuboot # Do not use this one, Nordic has it's own fork.
          # - mipi-sys-t
          # - nanopb
          # - net-tools
          - nrf_hw_models
          # - open-amp
          # - openthread
          - picolibc
          - psa-arch-tests
          - segger
          - sof
          # - tflite-micro
          - tinycrypt
          # - TraceRecorderSource
          # - trusted-firmware-m
          # - trusted-firmware-a
          - tf-m-tests
          # - uoscore-uedhoc
          - zcbor
          # - zscilib
          # - thrift

    # irnas drivers and modules
    - name: irnas-versioninfo-lib
      repo-path: irnas-versioninfo-lib
      path: irnas/irnas-versioninfo-lib
      remote: irnas
      revision: v1.1.1
